### ISSUE TITLE
crop_label.py

### ISSUE THREAD

**Issue by BetterSgc** [yisun98/SOLC#10]
你好，在tools文件夹下，存在两个crop_label.py,分别在SAR-optical文件夹和wos10文件夹下，请问一下你在README的第三部分里的   $ python tools/convert_lbl.py和 $ python tools/crop_lbl.py该使用哪个文件夹下的？另外wos10文件夹里的文件是用来干嘛的？谢谢了。

**Comment by yisun98** [comment]
已加联系方式回复。

**Comment by RayLu0214** [comment]
同问，想请问是用哪一个?

**Comment by 1219214501** [comment]
> 你好，在tools文件夹下，存在两个crop_label.py,分别在SAR-optical文件夹和wos10文件夹下，请问一下你在README的第三部分里的 $ python tools/convert_lbl.py和 $ python tools/crop_lbl.py该使用哪个文件夹下的？另外wos10文件夹里的文件是用来干嘛的？谢谢了。

你好，请问解决了吗，我也想了解这个问题

**Comment by mengcx0209** [comment]
> 你好，在tools文件夹下，存在两个crop_label.py,分别在SAR-optical文件夹和wos10文件夹下，请问一下你在README的第三部分里的 $ python tools/convert_lbl.py和 $ python tools/crop_lbl.py该使用哪个文件夹下的？另外wos10文件夹里的文件是用来干嘛的？谢谢了。

我也有这疑问。期待回复。
