### ISSUE TITLE
请教一下模型问题

### ISSUE THREAD

**Issue by czmky** [yisun98/SOLC#11]
Mcanet那篇论文中的模型是这个mcanet还是solc v7呢
我看这里面的mcanet怎么把mcam那里注释掉了
请问对照实验的模型能不能发布一下
万分感谢

**Comment by yisun98** [comment]
mcam有问题：1. mcam会导致模型的训练极其不稳定，且爆显存  2. mcam我按照论文中实现，发现原来的mcam模块是存在问题的，可以仔细看一下mcam模块的维度，在最后做点积的时候是无法对应起来的

**Comment by czmky** [comment]
好的，所以solc v7就是改进过后的mcanet嘛，我现在想要做个对照实验，请问大佬可以分享一下pscnn，mrsdc，V-fusunet和mbfnet的模型嘛

**Comment by yisun98** [comment]
感谢关注。

如果觉得我们的SOLC仓库对您有帮助，欢迎star和fork。祝好。 有问题可随时联系。

这几个模型我真不知道啊呜呜呜

**Comment by yisun98** [comment]
感谢关注。

如果觉得我们的SOLC仓库对您有帮助，欢迎star和fork。祝好。 有问题可随时联系。

solc v7是在mcanet的基础上改进的

**Comment by czmky** [comment]
请问怎么找这些model，我看有些文章里面模型具体都没写清楚

**Comment by czmky** [comment]
请教一下，他这backbone不是五个卷积块嘛，为什么mca论文里写的是res101
