### ISSUE TITLE
二分类问题

### ISSUE THREAD

**Issue by hwj0711** [yisun98/SOLC#13]
您好！这个模型能解决二分类问题吗 需要改哪些参数呢？我新加了一个
def one_classes():
        return ['其他类别',
                '建筑']
但是报错了
RuntimeError: weight tensor should be defined either for all or no classes

**Comment by gosling123456** [comment]
你好，请问solc solc2 solc3 solc4 solc5的models能开源吗？

Hello, can the models of solc solc2 solc3 solc4 solc5 be open sourced？

**Comment by yisun98** [comment]
> 您好！这个模型能解决二分类问题吗 需要改哪些参数呢？我新加了一个 def one_classes(): return ['其他类别', '建筑'] 但是报错了 RuntimeError: weight tensor should be defined either for all or no classes

建议检查一下代码，除了类别，交叉熵中的weights同样需要调整，模型的输出通道数也需要调整。该模型是完全支持二分类的，个人测试过。

**Comment by yisun98** [comment]
> 你好，请问solc solc2 solc3 solc4 solc5的models能开源吗？
> 
> Hello, can the models of solc solc2 solc3 solc4 solc5 be open sourced？

solc 1-5均为solc v7的迭代/测试版本，其架构繁琐，精度较低，有很多冗余部分，不建议读者使用，故没有选择公开。建议以solcv7为准，该模型经过完备的调试。
