### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by gosling123456** [yisun98/SOLC#14]
Traceback (most recent call last):
  File "D:\Master\CODE\SOLC\predict.py", line 169, in <module>
    reference()
  File "D:\Master\CODE\SOLC\predict.py", line 160, in reference
    model.load_state_dict(new_state_dict)
  File "D:\APP\Anaconda\envs\cv\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MCANet:
	Missing key(s) in state_dict: "aspp.0.stages.c0.conv.weight", "aspp.0.stages.c0.bn.weight", "aspp.0.stages.c0.bn.bias", "aspp.0.stages.c0.bn.running_mean", "aspp.0.stages.c0.bn.running_var", "aspp.0.stages.c1.conv.weight", "aspp.0.stages.c1.bn.weight", "aspp.0.stages.c1.bn.bias", "aspp.0.stages.c1.bn.running_mean", "aspp.0.stages.c1.bn.running_var", "aspp.0.stages.c2.conv.weight", "aspp.0.stages.c2.bn.weight", "aspp.0.stages.c2.bn.bias", "aspp.0.stages.c2.bn.running_mean", "aspp.0.stages.c2.bn.running_var", "aspp.0.stages.c3.conv.weight", "aspp.0.stages.c3.bn.weight", "aspp.0.stages.c3.bn.bias", "aspp.0.stages.c3.bn.running_mean", "aspp.0.stages.c3.bn.running_var", "aspp.0.stages.imagepool.conv.conv.weight", "aspp.0.stages.imagepool.conv.bn.weight", "aspp.0.stages.imagepool.conv.bn.bias", "aspp.0.stages.imagepool.conv.bn.running_mean", "aspp.0.stages.imagepool.conv.bn.running_var", "aspp.1.weight", "aspp.1.bias", "low_level_mcam.g_sar.weight", "low_level_mcam.g_sar.bias", "low_level_mcam.g_opt.weight", "low_level_mcam.g_opt.bias", "low_level_mcam.W.weight", "low_level_mcam.W.bias", "low_level_mcam.theta_sar.weight", "low_level_mcam.theta_sar.bias", "low_level_mcam.theta_opt.weight", "low_level_mcam.theta_opt.bias", "low_level_mcam.phi_sar.weight", "low_level_mcam.phi_sar.bias", "low_level_mcam.phi_opt.weight", "low_level_mcam.phi_opt.bias", "high_level_mcam.g_sar.weight", "high_level_mcam.g_sar.bias", "high_level_mcam.g_opt.weight", "high_level_mcam.g_opt.bias", "high_level_mcam.W.weight", "high_level_mcam.W.bias", "high_level_mcam.theta_sar.weight", "high_level_mcam.theta_sar.bias", "high_level_mcam.theta_opt.weight", "high_level_mcam.theta_opt.bias", "high_level_mcam.phi_sar.weight", "high_level_mcam.phi_sar.bias", "high_level_mcam.phi_opt.weight", "high_level_mcam.phi_opt.bias", "low_level_down.weight", "low_level_down.bias", "final.0.weight", "final.0.bias", "final.1.weight", "final.1.bias", "final.2.weight", "final.2.bias". 
	Unexpected key(s) in state_dict: "aspp.branch0.0.conv.weight", "aspp.branch0.0.bn.weight", "aspp.branch0.0.bn.bias", "aspp.branch0.0.bn.running_mean", "aspp.branch0.0.bn.running_var", "aspp.branch0.0.bn.num_batches_tracked", "aspp.branch0.1.conv.weight", "aspp.branch0.1.bn.weight", "aspp.branch0.1.bn.bias", "aspp.branch0.1.bn.running_mean", "aspp.branch0.1.bn.running_var", "aspp.branch0.1.bn.num_batches_tracked", "aspp.branch0.2.conv.weight", "aspp.branch0.2.bn.weight", "aspp.branch0.2.bn.bias", "aspp.branch0.2.bn.running_mean", "aspp.branch0.2.bn.running_var", "aspp.branch0.2.bn.num_batches_tracked", "aspp.branch1.0.conv.weight", "aspp.branch1.0.bn.weight", "aspp.branch1.0.bn.bias", "aspp.branch1.0.bn.running_mean", "aspp.branch1.0.bn.running_var", "aspp.branch1.0.bn.num_batches_tracked", "aspp.branch1.1.conv.weight", "aspp.branch1.1.bn.weight", "aspp.branch1.1.bn.bias", "aspp.branch1.1.bn.running_mean", "aspp.branch1.1.bn.running_var", "aspp.branch1.1.bn.num_batches_tracked", "aspp.branch1.2.conv.weight", "aspp.branch1.2.bn.weight", "aspp.branch1.2.bn.bias", "aspp.branch1.2.bn.running_mean", "aspp.branch1.2.bn.running_var", "aspp.branch1.2.bn.num_batches_tracked", "aspp.branch2.0.conv.weight", "aspp.branch2.0.bn.weight", "aspp.branch2.0.bn.bias", "aspp.branch2.0.bn.running_mean", "aspp.branch2.0.bn.running_var", "aspp.branch2.0.bn.num_batches_tracked", "aspp.branch2.1.conv.weight", "aspp.branch2.1.bn.weight", "aspp.branch2.1.bn.bias", "aspp.branch2.1.bn.running_mean", "aspp.branch2.1.bn.running_var", "aspp.branch2.1.bn.num_batches_tracked", "aspp.branch2.2.conv.weight", "aspp.branch2.2.bn.weight", "aspp.branch2.2.bn.bias", "aspp.branch2.2.bn.running_mean", "aspp.branch2.2.bn.running_var", "aspp.branch2.2.bn.num_batches_tracked", "aspp.branch2.3.conv.weight", "aspp.branch2.3.bn.weight", "aspp.branch2.3.bn.bias", "aspp.branch2.3.bn.running_mean", "aspp.branch2.3.bn.running_var", "aspp.branch2.3.bn.num_batches_tracked", "aspp.branch3.0.conv.weight", "aspp.branch3.0.bn.weight", "aspp.branch3.0.bn.bias", "aspp.branch3.0.bn.running_mean", "aspp.branch3.0.bn.running_var", "aspp.branch3.0.bn.num_batches_tracked", "aspp.branch3.1.conv.weight", "aspp.branch3.1.bn.weight", "aspp.branch3.1.bn.bias", "aspp.branch3.1.bn.running_mean", "aspp.branch3.1.bn.running_var", "aspp.branch3.1.bn.num_batches_tracked", "aspp.branch3.2.conv.weight", "aspp.branch3.2.bn.weight", "aspp.branch3.2.bn.bias", "aspp.branch3.2.bn.running_mean", "aspp.branch3.2.bn.running_var", "aspp.branch3.2.bn.num_batches_tracked", "aspp.branch3.3.conv.weight", "aspp.branch3.3.bn.weight", "aspp.branch3.3.bn.bias", "aspp.branch3.3.bn.running_mean", "aspp.branch3.3.bn.running_var", "aspp.branch3.3.bn.num_batches_tracked", "aspp.branch4.conv.conv.weight", "aspp.branch4.conv.bn.weight", "aspp.branch4.conv.bn.bias", "aspp.branch4.conv.bn.running_mean", "aspp.branch4.conv.bn.running_var", "aspp.branch4.conv.bn.num_batches_tracked", "aspp.ConvLinear.conv.weight", "aspp.ConvLinear.bn.weight", "aspp.ConvLinear.bn.bias", "aspp.ConvLinear.bn.running_mean", "aspp.ConvLinear.bn.running_var", "aspp.ConvLinear.bn.num_batches_tracked", "aspp.shortcut.conv.weight", "aspp.shortcut.bn.weight", "aspp.shortcut.bn.bias", "aspp.shortcut.bn.running_mean", "aspp.shortcut.bn.running_var", "aspp.shortcut.bn.num_batches_tracked", "low_level_down.fusion1.weight", "low_level_down.fusion1.bias", "low_level_down.gate.0.weight", "low_level_down.gate.2.weight", "low_level_down.fusion2.weight", "low_level_down.fusion2.bias". 
	size mismatch for decoder.1.weight: copying a param with shape torch.Size([8, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([8, 256, 3, 3]).

**Comment by yisun98** [comment]
这个是权重文件与模型不匹配导致的，建议检查一下模型的流程，以及中间的特征维度和大小。
