### ISSUE TITLE
想了解SAGate模块应该看哪篇论文

### ISSUE THREAD

**Issue by Shixinlong123** [yisun98/SOLC#17]
作者您好，注意到您在网络实现上使用了SAGate模块，请问它来自哪篇论文呢？

**Comment by TheGameLife** [comment]
Bi-directional Cross-Modality Feature
Propagation with Separation-and-Aggregation
Gate for RGB-D Semantic Segmentation

**Comment by Shixinlong123** [comment]
好的，收到，谢谢
&nbsp;


king小龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月14日(星期五) 下午4:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yisun98/SOLC] 想了解SAGate模块应该看哪篇论文 (Issue #17)














 
Bi-directional Cross-Modality Feature
 Propagation with Separation-and-Aggregation
 Gate for RGB-D Semantic Segmentation
