### ISSUE TITLE
MCANet运行结果的OA和Kappa低

### ISSUE THREAD

**Issue by cangkk1212** [yisun98/SOLC#18]
最近按照readme里所列参数跑了您复现的MCANet代码，但是测试的OA和Kappa的精度要比您的结果低1%左右，请问可能是有什么问题呢？

**Comment by lcflllcf** [comment]
你好，我也遇到了这个问题，请问你解决了吗？想请教一下~

**Comment by cangkk1212** [comment]
> 你好，我也遇到了这个问题，请问你解决了吗？想请教一下~

你好，我用了作者分享的预训练权重进行test依然低1%，我猜想可能是因为我的数据集是用作者代码划分的，但是作者分享的数据集划分好像有所不同，可能和这个有关系。不过我没有再进行实验验证
