### ISSUE TITLE
有关复现准确率的问题

### ISSUE THREAD

**Issue by lcflllcf** [yisun98/SOLC#19]
想问一下各位复现代码的朋友们，下载whu_opt_sar数据集以后是不是直接用crop.py进行图像的裁剪然后开始训练的呢？我在复现代码的时候各个参数都没有进行改动，但是准确率始终只能达到76%左右，大家是不是还做了什么图像增强的操作，以及如何才能达到81%左右的准确率？

**Comment by yisun98** [comment]
crop对模型性能的测试存在一定的影响，因为crop后split是随机的过程。如果需要达到readme中的准确率，可以使用本项目提供的数据集（crop和split后），从而对模型性能进行控制变量分析。

**Comment by lcflllcf** [comment]
感谢回复！项目中使用crop和split后的数据集链接能否提供？readme中的数据集网盘链接打开还是以前没有经过crop处理过的原始数据集~

**Comment by yisun98** [comment]
我已提供，可在readme "Release Our SOLC V7 weights solcv7: [baiduyun](https://pan.baidu.com/s/17DaI3e5alCWq2etOZDW5WQ) password：solc" 找到

**Comment by lcflllcf** [comment]
非常感谢！
