### ISSUE TITLE
About  dataset

### ISSUE THREAD

**Issue by XiaoxxWang** [yisun98/SOLC#2]
Hi, thanks for sharing your work. I have a question about the data. The optical images of the data from Baiduyun link all have grid mosaic. Do you have plans to share clear data?

**Comment by yisun98** [comment]
Thanks for your attention. Please refer to "https://github.com/AmberHen/WHU-OPT-SAR-dataset" for details. This link provides the source data.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yisun98/SOLC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月28日(星期三) 晚上8:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yisun98/SOLC] About  dataset (Issue #2)





 
Hi, thanks for sharing your work. I have a question about the data. The optical images of the data from Baiduyun link all have grid mosaic. Do you have plans to share clear data?

**Comment by XiaoxxWang** [comment]
Thanks a lot
