### ISSUE TITLE
您好，mdoels文件夹下的模型好像缺少了对比试验的几个模型。

### ISSUE THREAD

**Issue by yuxin7** [yisun98/SOLC#4]
例如train.py文件中的这几个模型：

from models.SOLC.solc import SOLC
from models.SOLCV2.solcv2 import SOLCV2
from models.SOLCV3.solcv3 import SOLCV3_res50
from models.SOLCV4.solcv4 import SOLCV4
from models.SOLCV5.solcv5 import SOLCV5
from models.HDC.duc_hdc import ResNetDUC等。

**Comment by yisun98** [comment]
感谢关注。SOLC、SOLCV2、SOLCV3_res50、SOLCV4、SOLCV5为实验迭代版本，效果并不理想，其最终模型为SOLCV7。ResNetDUC该模型，是之前框架遗留下来的，我暂未使用到该模型。可以将这些模型从代码中移除即可。

**Comment by yuxin7** [comment]
还有一个问题想咨询一下您， 我看您最终模型的精度为：dcn(ours)  | 0.8222 | 0.4382   | 0.7428    | ，但您共享在百度网盘的最终的模型的精度为：
![image](https://user-images.githubusercontent.com/35183358/227092390-7a5add45-ac5b-4da6-b4ba-05b48fa094e7.png)
。两者的精度好像不一致。

**Comment by yuxin7** [comment]
还有一个问题，就是我看最终您提供的模型要求光学的数据输入为维的，但代码中读取光学数据的部分却使用的时使用的是PIL库读取的， img_opt = Image.open(img_opt_path)，这样读取的数据维度只有3维。

**Comment by yisun98** [comment]
> 感谢关注。百度网盘上传的权值 精度 表示是train/val阶段的精度，而最终模型的精度是在test上得到的精度
