### ISSUE TITLE
关于测试数据集

### ISSUE THREAD

**Issue by Wu-Xinyu** [yisun98/SOLC#5]
您好，非常感谢您分享的代码。您的代码test.py中数据集文件为‘GF2_PMS2_E115.9_N39.0_20170225_L1A0002206085-MSS2.csv’，这个文件中涉及到的图片都是光学图像嘛？有公开嘛？谢谢。

**Comment by Wu-Xinyu** [comment]
另外想咨询一下您了解还有其他公开的SAR与多光谱用于语义分割的数据集嘛？感谢感谢

**Comment by yisun98** [comment]
> 感谢关注。代码中的test.py是之前项目的遗留文件，实际上test.py在SOLC工程中并未使用到。请使用predict.py即可。

**Comment by yisun98** [comment]
> 另外想咨询一下您了解还有其他公开的SAR与多光谱用于语义分割的数据集嘛？感谢感谢

感谢关注。由于个人并不是主要做SAR和多光谱图像的语义分割，因此数据集了解的并不多。个人主要做多源图像融合。选择SAR和多光谱做语义分割是因为当时的课题报告需求。

**Comment by Wu-Xinyu** [comment]
感谢您的回复！
