### ISSUE TITLE
关于运行predict.py文件

### ISSUE THREAD

**Issue by XingLongH** [yisun98/SOLC#6]
您好，非常感谢您分享的代码。我train完了之后，用训练好的模型跑predict.py时，精度特别低是怎么回事呢？
比如我训练：
训练完后   epoch 39 的  oa ：0.76148   kappa ：0.67744

但是用时   epoch 39 oa 0.76148 kappa 0.67744 latest.pth   跑  predict.py  时，oa ：0.084   kappa ：-0.0048

**Comment by Wu-Xinyu** [comment]
你好，我想问下 您训练的精度最高是0.76嘛 我训练的精度最高只能达到0.75左右，但是论文中作者训练的精度达到了0.829，不知道是什么原因。谢谢！

**Comment by yisun98** [comment]
> 
感谢关注。

因为训练的oa和kappa是正常的，但是在测试上oa没有达到0.1，以及kappa居然还出现了负数，这是需要排查的。个人觉得，可能是训练权重未正确加载，或者模型未正确加载，或者测试的sar-opt图片不对应导致的。若以上推测均排除，则我也确实不知道因为什么了。但肯定的是，不可能是过拟合。因为即便是过拟合，测试的性能也不至于出现上述情况。

如果觉得我们的SOLC仓库对您有帮助，欢迎star和fork。祝好。有问题可随时联系。

**Comment by yisun98** [comment]
> 你好，我想问下 您训练的精度最高是0.76嘛 我训练的精度最高只能达到0.75左右，但是论文中作者训练的精度达到了0.829，不知道是什么原因。谢谢！

感谢关注。

训练的精度最高并未详细统计过，当时训练SOLC V7模型，就只训练了一次得到了较为理想的结果便没有再去二次训练。若训练精度最高0.76，您训练最高是0.75，我觉得是正常的，这个偏差不大，实验可能会受训练设备、Cuda版本、训练初始情况、随机种子等诸多因素的影响，只要精度误差在+-5%左右，我觉得都是可以接受的。
至于论文中的作者训练精度达到了0.829，我曾向作者请求工程代码，但暂未得到回复，所以我就自己复现了。至于作者的0.829，我是真不知道为什么会这么高，可能是评估的指标计算方式不一致，或是其他因素。

目前所有的模型均在自己划分的数据集下统一评估，个人觉得是没有问题的，所有的模型都在同一环境下，精度要高都高，要低都低。

如果觉得我们的SOLC仓库对您有帮助，欢迎star和fork。祝好。有问题可随时联系。
