### ISSUE TITLE
dataset.py

### ISSUE THREAD

**Issue by BetterSgc** [yisun98/SOLC#8]
你好，请问一下在dataset.py里的第39，40，42，43行的root报错，错误显示unresolved reference，我该如何更改这个错误？谢谢了

**Comment by yisun98** [comment]
感谢关注。

我们并未使用RSDataset数据加载类，而是使用WHUOPTSARDataset数据加载类。

在dataset.py里的第39，40，42，43行的root报错，是RSDataset数据加载类出现了错误，不影响SOLC工程源代码的运行。

如果您需要使用RSDataset数据加载类，可以和我说一下，我将会修复这个bug。

**如果觉得我们的SOLC仓库对您有帮助，欢迎star和fork。祝好。** 有问题可随时联系。

**Comment by BetterSgc** [comment]
感谢回复！我通过主页的联系方式给你发了一份QQ邮件，还有一些更深入的问题想交流一下。
